kind: TestWorkflow
apiVersion: testworkflows.testkube.io/v1
metadata:
  name: basic-echo-sleep-local
  namespace: testkube
  labels:
    health: icon
    se-demo: sandbox
spec:
  config:
    sleepyTime:
      type: integer
      default: 5
  container:
    workingDir: /data/repo
    image: bash:devel-alpine3.22
  pod:
    volumes:
    - name: devcode
      persistentVolumeClaim:
        claimName: tilt-dev-pvc
  execution:
    tags:
      test: sleeping
    target:
      match:
        name:
        - testkube2
  services:
    local-dev-looper:
      content:
        files:
        - path: /scripts/check.sh
          content: |
            #!/bin/sh
            set -euo pipefail
            MOUNT_PATH="/data/repo"
            DIR_TO_FIND="basic-echo-sleep-local"
            FULL_PATH="$MOUNT_PATH/$DIR_TO_FIND"
            echo "--- File Sync Check Service ---"
            echo "Waiting for directory to appear at: $FULL_PATH"
            echo "(This directory should be created on your local machine and synced by Tilt)"
            while true; do
              if [ -d "$FULL_PATH" ]; then
                echo "Success! Directory '$FULL_PATH' found."
                exit 0
              fi
              echo "Directory not found yet. Retrying in 5 seconds..."
              sleep 5
            done
      pod:
        volumes:
        - name: devcode
          persistentVolumeClaim:
            claimName: tilt-dev-pvc
      image: bash:devel-alpine3.22
      command:
      - /bin/sh
      - /scripts/check.sh
      volumeMounts:
      - name: devcode
        mountPath: /data/repo
  steps:
  - name: Sleeping...
    run:
      image: bash:devel-alpine3.22
      args:
      - bash
      - -euo
      - pipefail
      - -c
      - |
        TOTAL={{config.sleepyTime}}
        if (( TOTAL <= 180 )); then
          INTERVAL=10
        else
          INTERVAL=30
        fi

        REMAIN=$TOTAL
        while (( REMAIN > 0 )); do
          echo "Sleeping for $REMAIN more seconds..."
          if (( REMAIN > INTERVAL )); then
            sleep "$INTERVAL"
            REMAIN=$(( REMAIN - INTERVAL ))
          else
            sleep "$REMAIN"
            REMAIN=0
          fi
        done
        echo "Done sleeping for $TOTAL seconds."
        echo "This is new line"
        cat /data/repo/sync_probe.txt
      volumeMounts:
      - name: devcode
        mountPath: /data/repo
  - name: Waking up...
    shell: |-
      cat <<'SUN'
              .     :     .
            .  :    |    :  .
             .  |   |   |  ,
              \  |     |  /
          .     ,-'"""`-.     .
            "- /  __ __  \ -"
              |==|  I  |==|
        - --- | _`--^--'_ | --- -
              |'`.     ,'`|
            _- \  "---"  / -_
          .     `-.___,-'     .
              /  |     |  \
            .'  |   |   |  `.
               :    |    :
              .     :     .
status:
  health:
    passRate: 1
    flipRate: 0
    overallHealth: 1
