kind: TestWorkflow
apiVersion: testworkflows.testkube.io/v1
metadata:
  name: loop-driver
  namespace: testkube
spec:
  services:
    cli-runner:
      logs: always
      content:
        files:
        - path: /scripts/loop.sh
          content: |
            #!/bin/sh
            set -eu
            testkube set context --api-key tkcapi_c00f46f2348e8cef36952eb2a4b704 --org tkcorg_c6b4dc0ce62fd50a --env tkcenv_2a833be8f77302c9
            while true; do
              echo "Triggering workflow..."
              # Use in-cluster client so the CLI talks to the Agent inside the cluster.
              # If you set TESTKUBE_NAMESPACE, it will be used; otherwise CLI default applies.
              testkube run tw loop-target

              # Pause between loops so each execution can finish before the next one starts.
              sleep 20
            done
      image: kubeshop/testkube-cli:latest
      command:
      - /bin/sh
      - -lc
      - |
        exec /bin/sh /scripts/loop.sh
  steps:
  - name: keep-alive
    run:
      image: bash:devel-alpine3.22
      shell: sleep 300
status:
  health:
    passRate: 0.5
    flipRate: 0.2
    overallHealth: 0.4

